export interface RuleItem {
  id: number;
  type?: string;
  pid: number;
  name: string;
  title: string;
  icon: string;
  condition: string;
  remark: string;
  ismenu: number;
  createtime?: number | null;
  updatetime?: number | null;
  weigh: number;
  status: "normal" | "hidden";
  subnode?: number;
  is_agent_menu?: number;
  spacer?: string;
  haschild?: number;
}

export const INITIAL_RULES: RuleItem[] = [
  {
    "id": 1,
    "type": "file",
    "pid": 0,
    "name": "dashboard",
    "title": " 控制台",
    "icon": "fa fa-dashboard",
    "condition": "",
    "remark": "Dashboard tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1566108533,
    "weigh": 10000,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 13,
    "type": "file",
    "pid": 1,
    "name": "dashboard/index",
    "title": "&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 136,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 14,
    "type": "file",
    "pid": 1,
    "name": "dashboard/add",
    "title": "&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 135,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 16,
    "type": "file",
    "pid": 1,
    "name": "dashboard/edit",
    "title": "&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 134,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 15,
    "type": "file",
    "pid": 1,
    "name": "dashboard/del",
    "title": "&nbsp;├ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 133,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 17,
    "type": "file",
    "pid": 1,
    "name": "dashboard/multi",
    "title": "&nbsp;└ Multi",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 132,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 96,
    "type": "file",
    "pid": 0,
    "name": "order",
    "title": " 订单管理",
    "icon": "fa fa-list-ol",
    "condition": "",
    "remark": "订单管理",
    "ismenu": 1,
    "createtime": 1559215774,
    "updatetime": 1601632748,
    "weigh": 9999,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 146,
    "type": "file",
    "pid": 96,
    "name": "order/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162325,
    "updatetime": 1560162325,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 147,
    "type": "file",
    "pid": 96,
    "name": "order/del",
    "title": "&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162361,
    "updatetime": 1560162361,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 148,
    "type": "file",
    "pid": 96,
    "name": "order/detail",
    "title": "&nbsp;├ 详情",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162408,
    "updatetime": 1560162408,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 218,
    "type": "file",
    "pid": 96,
    "name": "order/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254552,
    "updatetime": 1600254552,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 219,
    "type": "file",
    "pid": 96,
    "name": "order/multi",
    "title": "&nbsp;└ 批量",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254627,
    "updatetime": 1600254627,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 66,
    "type": "file",
    "pid": 0,
    "name": "user",
    "title": " 会员管理",
    "icon": "fa fa-users",
    "condition": "",
    "remark": "会员管理",
    "ismenu": 1,
    "createtime": 1516374729,
    "updatetime": 1601632759,
    "weigh": 9998,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 125,
    "type": "file",
    "pid": 66,
    "name": "user/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160371,
    "updatetime": 1560160371,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 126,
    "type": "file",
    "pid": 66,
    "name": "user/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160387,
    "updatetime": 1560160387,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 127,
    "type": "file",
    "pid": 66,
    "name": "user/del",
    "title": "&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160405,
    "updatetime": 1560160405,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 128,
    "type": "file",
    "pid": 66,
    "name": "user/detail",
    "title": "&nbsp;├ 详情",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160462,
    "updatetime": 1560160462,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 129,
    "type": "file",
    "pid": 66,
    "name": "user/score",
    "title": "&nbsp;├ 上下分",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160495,
    "updatetime": 1560160495,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 130,
    "type": "file",
    "pid": 66,
    "name": "user/chat",
    "title": "&nbsp;├ 私信",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160528,
    "updatetime": 1560160528,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 131,
    "type": "file",
    "pid": 66,
    "name": "user/report",
    "title": "&nbsp;├ 报表",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160582,
    "updatetime": 1560160582,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 132,
    "type": "file",
    "pid": 66,
    "name": "user/multi",
    "title": "&nbsp;├ 批量启用/冻结会员",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560160683,
    "updatetime": 1560160683,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 175,
    "type": "file",
    "pid": 66,
    "name": "use/check",
    "title": "&nbsp;├ 设置/取消假人",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1561088492,
    "updatetime": 1561088492,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 228,
    "type": "file",
    "pid": 66,
    "name": "user/add",
    "title": "&nbsp;└ 添加",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1692680105,
    "updatetime": 1692680105,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 97,
    "type": "file",
    "pid": 0,
    "name": "upmark",
    "title": " 充值管理",
    "icon": "fa fa-hand-o-up",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1559215875,
    "updatetime": 1601632768,
    "weigh": 9997,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 149,
    "type": "file",
    "pid": 97,
    "name": "upmark/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162591,
    "updatetime": 1560162591,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 150,
    "type": "file",
    "pid": 97,
    "name": "upmark/del",
    "title": "&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162612,
    "updatetime": 1560162612,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 151,
    "type": "file",
    "pid": 97,
    "name": "upmark/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162629,
    "updatetime": 1560162629,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 152,
    "type": "file",
    "pid": 97,
    "name": "upmark/multi",
    "title": "&nbsp;├ 批量处理",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560162812,
    "updatetime": 1560162812,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 173,
    "type": "file",
    "pid": 97,
    "name": "upmark/check",
    "title": "&nbsp;└ 审核",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560944413,
    "updatetime": 1560944413,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 98,
    "type": "file",
    "pid": 0,
    "name": "downmark",
    "title": " 提现管理",
    "icon": "fa fa-hand-o-down",
    "condition": "",
    "remark": "下分记录",
    "ismenu": 1,
    "createtime": 1559215936,
    "updatetime": 1601632775,
    "weigh": 9996,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 153,
    "type": "file",
    "pid": 98,
    "name": "downmark/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560163071,
    "updatetime": 1560163071,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 154,
    "type": "file",
    "pid": 98,
    "name": "downmark/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560163085,
    "updatetime": 1560163085,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 155,
    "type": "file",
    "pid": 98,
    "name": "downmark/del",
    "title": "&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560163100,
    "updatetime": 1560163100,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 156,
    "type": "file",
    "pid": 98,
    "name": "downmark/multi",
    "title": "&nbsp;├ 批量处理",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560163133,
    "updatetime": 1560163133,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 174,
    "type": "file",
    "pid": 98,
    "name": "downmark/check",
    "title": "&nbsp;└ 审核",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1560944462,
    "updatetime": 1560944462,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 203,
    "type": "file",
    "pid": 0,
    "name": "product",
    "title": " 产品管理",
    "icon": "fa fa-shopping-bag",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1599458113,
    "updatetime": 1599458113,
    "weigh": 9996,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 204,
    "type": "file",
    "pid": 203,
    "name": "product/product",
    "title": "&nbsp;├ 产品列表",
    "icon": "fa fa-shopping-bag",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1599458443,
    "updatetime": 1599458443,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 208,
    "type": "file",
    "pid": 204,
    "name": "product/product/index",
    "title": "&nbsp;│&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600253897,
    "updatetime": 1600253897,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 209,
    "type": "file",
    "pid": 204,
    "name": "product/product/add",
    "title": "&nbsp;│&nbsp;├ 添加",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600253910,
    "updatetime": 1600253910,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 210,
    "type": "file",
    "pid": 204,
    "name": "product/product/edit",
    "title": "&nbsp;│&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600253926,
    "updatetime": 1600253926,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 211,
    "type": "file",
    "pid": 204,
    "name": "product/product/del",
    "title": "&nbsp;│&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600253944,
    "updatetime": 1600253944,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 212,
    "type": "file",
    "pid": 204,
    "name": "product/product/multi",
    "title": "&nbsp;│&nbsp;└ 批量",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600253996,
    "updatetime": 1600253996,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 205,
    "type": "file",
    "pid": 203,
    "name": "product/type",
    "title": "&nbsp;└ 产品分类",
    "icon": "fa fa-list-alt",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1599458485,
    "updatetime": 1599458485,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 1
  },
  {
    "id": 213,
    "type": "file",
    "pid": 205,
    "name": "product/type/add",
    "title": "&nbsp;&nbsp;&nbsp;├ 添加",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254023,
    "updatetime": 1600254023,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 214,
    "type": "file",
    "pid": 205,
    "name": "product/type/edit",
    "title": "&nbsp;&nbsp;&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254034,
    "updatetime": 1600254034,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 215,
    "type": "file",
    "pid": 205,
    "name": "product/type/index",
    "title": "&nbsp;&nbsp;&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254047,
    "updatetime": 1600254047,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 216,
    "type": "file",
    "pid": 205,
    "name": "product/type/del",
    "title": "&nbsp;&nbsp;&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254060,
    "updatetime": 1600254060,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 217,
    "type": "file",
    "pid": 205,
    "name": "product/type/multi",
    "title": "&nbsp;&nbsp;&nbsp;└ 批量",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254076,
    "updatetime": 1600254076,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;└",
    "haschild": 0
  },
  {
    "id": 224,
    "type": "file",
    "pid": 0,
    "name": "exchange",
    "title": " 转换记录",
    "icon": "fa fa-money",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1600946271,
    "updatetime": 1601632785,
    "weigh": 9990,
    "status": "hidden",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 225,
    "type": "file",
    "pid": 224,
    "name": "exchange/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600946305,
    "updatetime": 1600946305,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 226,
    "type": "file",
    "pid": 224,
    "name": "exchange/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600946333,
    "updatetime": 1600946333,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 227,
    "type": "file",
    "pid": 224,
    "name": "exchange/del",
    "title": "&nbsp;└ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600946345,
    "updatetime": 1600946345,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 233,
    "type": "menu",
    "pid": 0,
    "name": "loan",
    "title": " 贷款管理",
    "icon": "fa fa-credit-card",
    "condition": "",
    "remark": "贷款功能管理",
    "ismenu": 1,
    "createtime": 1761622040,
    "updatetime": 1761622592,
    "weigh": 100,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 234,
    "type": "menu",
    "pid": 233,
    "name": "loan_config",
    "title": "&nbsp;├ 贷款配置管理",
    "icon": "fa fa-cog",
    "condition": "",
    "remark": "配置借款天数、日利率等",
    "ismenu": 1,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 98,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 235,
    "type": "file",
    "pid": 234,
    "name": "loan_config/index",
    "title": "&nbsp;│&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 236,
    "type": "file",
    "pid": 234,
    "name": "loan_config/add",
    "title": "&nbsp;│&nbsp;├ 添加",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 237,
    "type": "file",
    "pid": 234,
    "name": "loan_config/edit",
    "title": "&nbsp;│&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 238,
    "type": "file",
    "pid": 234,
    "name": "loan_config/del",
    "title": "&nbsp;│&nbsp;└ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 239,
    "type": "menu",
    "pid": 233,
    "name": "loan_record",
    "title": "&nbsp;└ 贷款记录管理",
    "icon": "fa fa-list",
    "condition": "",
    "remark": "查看用户贷款记录",
    "ismenu": 1,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 97,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 1
  },
  {
    "id": 240,
    "type": "file",
    "pid": 239,
    "name": "loan_record/index",
    "title": "&nbsp;&nbsp;&nbsp;└ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1761622040,
    "updatetime": 1761622040,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;└",
    "haschild": 0
  },
  {
    "id": 2,
    "type": "file",
    "pid": 0,
    "name": "general",
    "title": " 系统设置",
    "icon": "fa fa-cogs",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1601632736,
    "weigh": 9,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 6,
    "type": "file",
    "pid": 2,
    "name": "general/config",
    "title": "&nbsp;├ 网站配置",
    "icon": "fa fa-cog",
    "condition": "",
    "remark": "Config tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1594735016,
    "weigh": 9999,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 18,
    "type": "file",
    "pid": 6,
    "name": "general/config/index",
    "title": "&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 52,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 19,
    "type": "file",
    "pid": 6,
    "name": "general/config/add",
    "title": "&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 51,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 20,
    "type": "file",
    "pid": 6,
    "name": "general/config/edit",
    "title": "&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 50,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 21,
    "type": "file",
    "pid": 6,
    "name": "general/config/del",
    "title": "&nbsp;│&nbsp;├ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 49,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 22,
    "type": "file",
    "pid": 6,
    "name": "general/config/multi",
    "title": "&nbsp;│&nbsp;└ Multi",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 48,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 5,
    "type": "file",
    "pid": 2,
    "name": "auth",
    "title": "&nbsp;├ 权限管理",
    "icon": "fa fa-group",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1693818628,
    "weigh": 98,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 9,
    "type": "file",
    "pid": 5,
    "name": "auth/admin",
    "title": "&nbsp;│&nbsp;├ Admin",
    "icon": "fa fa-user",
    "condition": "",
    "remark": "Admin tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1497430320,
    "weigh": 118,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 1
  },
  {
    "id": 40,
    "type": "file",
    "pid": 9,
    "name": "auth/admin/index",
    "title": "&nbsp;│&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Admin tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 117,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 41,
    "type": "file",
    "pid": 9,
    "name": "auth/admin/add",
    "title": "&nbsp;│&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 116,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 42,
    "type": "file",
    "pid": 9,
    "name": "auth/admin/edit",
    "title": "&nbsp;│&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 115,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 43,
    "type": "file",
    "pid": 9,
    "name": "auth/admin/del",
    "title": "&nbsp;│&nbsp;│&nbsp;└ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 114,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 10,
    "type": "file",
    "pid": 5,
    "name": "auth/adminlog",
    "title": "&nbsp;│&nbsp;├ Admin log",
    "icon": "fa fa-list-alt",
    "condition": "",
    "remark": "Admin log tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1497430307,
    "weigh": 113,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 1
  },
  {
    "id": 44,
    "type": "file",
    "pid": 10,
    "name": "auth/adminlog/index",
    "title": "&nbsp;│&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Admin log tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 112,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 45,
    "type": "file",
    "pid": 10,
    "name": "auth/adminlog/detail",
    "title": "&nbsp;│&nbsp;│&nbsp;├ 详情",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 111,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 46,
    "type": "file",
    "pid": 10,
    "name": "auth/adminlog/del",
    "title": "&nbsp;│&nbsp;│&nbsp;└ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 110,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 11,
    "type": "file",
    "pid": 5,
    "name": "auth/group",
    "title": "&nbsp;│&nbsp;├ Group",
    "icon": "fa fa-group",
    "condition": "",
    "remark": "Group tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 109,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 1
  },
  {
    "id": 47,
    "type": "file",
    "pid": 11,
    "name": "auth/group/index",
    "title": "&nbsp;│&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Group tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 108,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 48,
    "type": "file",
    "pid": 11,
    "name": "auth/group/add",
    "title": "&nbsp;│&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 107,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 49,
    "type": "file",
    "pid": 11,
    "name": "auth/group/edit",
    "title": "&nbsp;│&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 106,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 50,
    "type": "file",
    "pid": 11,
    "name": "auth/group/del",
    "title": "&nbsp;│&nbsp;│&nbsp;└ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 105,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 12,
    "type": "file",
    "pid": 5,
    "name": "auth/rule",
    "title": "&nbsp;│&nbsp;└ 菜单规则",
    "icon": "fa fa-bars",
    "condition": "",
    "remark": "Rule tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1693818711,
    "weigh": 104,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 1
  },
  {
    "id": 51,
    "type": "file",
    "pid": 12,
    "name": "auth/rule/index",
    "title": "&nbsp;│&nbsp;&nbsp;&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Rule tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 103,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 52,
    "type": "file",
    "pid": 12,
    "name": "auth/rule/add",
    "title": "&nbsp;│&nbsp;&nbsp;&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 102,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 53,
    "type": "file",
    "pid": 12,
    "name": "auth/rule/edit",
    "title": "&nbsp;│&nbsp;&nbsp;&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 101,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 54,
    "type": "file",
    "pid": 12,
    "name": "auth/rule/del",
    "title": "&nbsp;│&nbsp;&nbsp;&nbsp;└ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 100,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;&nbsp;&nbsp;└",
    "haschild": 0
  },
  {
    "id": 3,
    "type": "file",
    "pid": 2,
    "name": "category",
    "title": "&nbsp;├ 图文管理",
    "icon": "fa fa-leaf",
    "condition": "",
    "remark": "Category tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1559208763,
    "weigh": 53,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 35,
    "type": "file",
    "pid": 3,
    "name": "category/index",
    "title": "&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Category tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 142,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 36,
    "type": "file",
    "pid": 3,
    "name": "category/add",
    "title": "&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 141,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 37,
    "type": "file",
    "pid": 3,
    "name": "category/edit",
    "title": "&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 140,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 38,
    "type": "file",
    "pid": 3,
    "name": "category/del",
    "title": "&nbsp;│&nbsp;├ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 139,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 39,
    "type": "file",
    "pid": 3,
    "name": "category/multi",
    "title": "&nbsp;│&nbsp;└ Multi",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 138,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 7,
    "type": "file",
    "pid": 2,
    "name": "general/attachment",
    "title": "&nbsp;├ Attachment",
    "icon": "fa fa-file-image-o",
    "condition": "",
    "remark": "Attachment tips",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1497430699,
    "weigh": 34,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 23,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/index",
    "title": "&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "Attachment tips",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 59,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 24,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/select",
    "title": "&nbsp;│&nbsp;├ Select attachment",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 58,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 25,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/add",
    "title": "&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 57,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 26,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/edit",
    "title": "&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 56,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 27,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/del",
    "title": "&nbsp;│&nbsp;├ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 55,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 28,
    "type": "file",
    "pid": 7,
    "name": "general/attachment/multi",
    "title": "&nbsp;│&nbsp;└ Multi",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 54,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 8,
    "type": "file",
    "pid": 2,
    "name": "general/profile",
    "title": "&nbsp;├ Profile",
    "icon": "fa fa-user",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 1
  },
  {
    "id": 29,
    "type": "file",
    "pid": 8,
    "name": "general/profile/index",
    "title": "&nbsp;│&nbsp;├ View",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 33,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 30,
    "type": "file",
    "pid": 8,
    "name": "general/profile/update",
    "title": "&nbsp;│&nbsp;├ Update profile",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 32,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 31,
    "type": "file",
    "pid": 8,
    "name": "general/profile/add",
    "title": "&nbsp;│&nbsp;├ Add",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 31,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 32,
    "type": "file",
    "pid": 8,
    "name": "general/profile/edit",
    "title": "&nbsp;│&nbsp;├ Edit",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 30,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 33,
    "type": "file",
    "pid": 8,
    "name": "general/profile/del",
    "title": "&nbsp;│&nbsp;├ Delete",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 29,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;├",
    "haschild": 0
  },
  {
    "id": 34,
    "type": "file",
    "pid": 8,
    "name": "general/profile/multi",
    "title": "&nbsp;│&nbsp;└ Multi",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1497429920,
    "updatetime": 1497429920,
    "weigh": 28,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;│&nbsp;└",
    "haschild": 0
  },
  {
    "id": 86,
    "type": "file",
    "pid": 2,
    "name": "general/database",
    "title": "&nbsp;└ 数据库管理",
    "icon": "fa fa-database",
    "condition": "",
    "remark": "可在线进行一些简单的数据库表优化或修复,查看表结构和数据。",
    "ismenu": 1,
    "createtime": 1559208137,
    "updatetime": 1576507040,
    "weigh": 0,
    "status": "hidden",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 1
  },
  {
    "id": 87,
    "type": "file",
    "pid": 86,
    "name": "general/database/index",
    "title": "&nbsp;&nbsp;&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1559208137,
    "updatetime": 1559208137,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 88,
    "type": "file",
    "pid": 86,
    "name": "general/database/query",
    "title": "&nbsp;&nbsp;&nbsp;├ 查询",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1559208137,
    "updatetime": 1559208137,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 89,
    "type": "file",
    "pid": 86,
    "name": "general/database/backup",
    "title": "&nbsp;&nbsp;&nbsp;├ 备份",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1559208137,
    "updatetime": 1559208137,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;├",
    "haschild": 0
  },
  {
    "id": 90,
    "type": "file",
    "pid": 86,
    "name": "general/database/restore",
    "title": "&nbsp;&nbsp;&nbsp;└ 恢复",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1559208137,
    "updatetime": 1559208137,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;&nbsp;&nbsp;└",
    "haschild": 0
  },
  {
    "id": 116,
    "type": "file",
    "pid": 0,
    "name": "general/config/cache",
    "title": " 数据清理",
    "icon": "fa fa-trash",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1560150533,
    "updatetime": 1595661382,
    "weigh": 0,
    "status": "hidden",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 0
  },
  {
    "id": 206,
    "type": "file",
    "pid": 0,
    "name": "notice",
    "title": " 新闻公告",
    "icon": "fa fa-newspaper-o",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1599884374,
    "updatetime": 1599884374,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 220,
    "type": "file",
    "pid": 206,
    "name": "notice/add",
    "title": "&nbsp;├ 添加",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254670,
    "updatetime": 1706535081,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 221,
    "type": "file",
    "pid": 206,
    "name": "notice/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254684,
    "updatetime": 1706535108,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 222,
    "type": "file",
    "pid": 206,
    "name": "notice/del",
    "title": "&nbsp;├ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254696,
    "updatetime": 1706535112,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 223,
    "type": "file",
    "pid": 206,
    "name": "notice/multi",
    "title": "&nbsp;└ 批量",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": 1600254718,
    "updatetime": 1706535116,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 229,
    "type": "file",
    "pid": 0,
    "name": "verify",
    "title": " 实名认证",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1754951846,
    "updatetime": 1754951846,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 242,
    "type": "file",
    "pid": 229,
    "name": "verify/index",
    "title": "&nbsp;├ 查看",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": null,
    "updatetime": null,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 243,
    "type": "file",
    "pid": 229,
    "name": "verify/edit",
    "title": "&nbsp;├ 编辑",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": null,
    "updatetime": null,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 244,
    "type": "file",
    "pid": 229,
    "name": "verify/detail",
    "title": "&nbsp;├ 详情",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": null,
    "updatetime": null,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 245,
    "type": "file",
    "pid": 229,
    "name": "verify/verify",
    "title": "&nbsp;├ 审核",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": null,
    "updatetime": null,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 246,
    "type": "file",
    "pid": 229,
    "name": "verify/del",
    "title": "&nbsp;└ 删除",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 0,
    "createtime": null,
    "updatetime": null,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 230,
    "type": "file",
    "pid": 0,
    "name": "yuebao",
    "title": " 余额宝管理",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1755311482,
    "updatetime": 1755311482,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 1
  },
  {
    "id": 231,
    "type": "file",
    "pid": 230,
    "name": "yuebao_order/index",
    "title": "&nbsp;├ 余额宝订单",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1755311517,
    "updatetime": 1755315615,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;├",
    "haschild": 0
  },
  {
    "id": 232,
    "type": "file",
    "pid": 230,
    "name": "yuebao_config",
    "title": "&nbsp;└ 余额宝配置",
    "icon": "fa fa-circle-o",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1755311547,
    "updatetime": 1755319419,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "&nbsp;└",
    "haschild": 0
  },
  {
    "id": 241,
    "type": "menu",
    "pid": 0,
    "name": "index/ipwhitelist",
    "title": " 后台IP白名单",
    "icon": "fa fa-shield",
    "condition": "",
    "remark": "",
    "ismenu": 1,
    "createtime": 1771849245,
    "updatetime": 1771850671,
    "weigh": 0,
    "status": "normal",
    "is_agent_menu": 0,
    "spacer": "",
    "haschild": 0
  }
];
